object BuildDependenciesVersions {
    const val androidGradlePlugin = "8.2.1"
    const val appcompat = "1.6.1"
    const val expresso = "3.5.1"
    const val fragment = "1.6.2"
    const val junit = "4.13.2"
    const val junitext = "1.1.5"
    const val koin = "3.3.3"
    const val kotlinPlugin = "1.9.0"
    const val ktx = "1.9.0"
    const val lifecycleViewmodel = "2.6.1"
    const val material = "1.11.0"
    const val materialIconsExtended = "1.4.3"
    const val moshi = "1.12.0"
    const val navigation = "2.5.3"
    const val okhttp = "4.9.1"
    const val picasso = "2.8"
    const val retrofit = "2.9.0"
    const val swiperefreshlayout = "1.1.0"
}
